### PR TITLE
globi.json is used to have GloBI auto-discover and configure datasets…

### PR DESCRIPTION
**Pull request by jhpoelen**
…, see https://github.com/hurlbertlab/dietdatabase/issues/40

Please merge this pull request to enable newly upgraded GloBI checker (see https://github.com/jhpoelen/eol-globi-data/releases/tag/v0.8.10) using travis.

### CODE REVIEW

**Comment by jhpoelen** [comment]
Thanks for merging. Look like the checker went ahead and found a bunch of warnings. Some of which are probably on a bug in the importer my end like:

```org.eol.globi.tool.GitHubRepoCheck - [hurlbertlab/dietdatabase]: [not setting collection date, because [1976] on line [946] could not be read as date.]``` 

Others I noticed are lines with empty source: 
```org.eol.globi.data.StudyImporterForHurlbert - missing source on line [1291]```

Could you please spotcheck those and see whether they are false negatives?

**Comment by ahhurlbert** [comment]
I confirmed that there is only a single record in the entire database with a missing source (line 11514), and I'm still looking into that. I spot checked many of the lines in the travis output and saw nothing obviously wrong.

**Comment by ahhurlbert** [comment]
All rows in the database should now have a valid source.

**Comment by jhpoelen** [comment]
@ahhurlbert thanks for double checking. I created an issue for the false negative warnings produced https://github.com/jhpoelen/eol-globi-data/issues/276 .  Hoping to address this issue sooner rather than later, so that the automated check would actually help detect future data errors instead.

**Pull request merged**
